(() => {
'use strict';
const URL_BASE='https://dqaooogkwjwiufnrrzpx.supabase.co';
const API_KEY='sb_publishable_DSqelI68t-0TnwjSGDF_Pg_zZ0uqfZB';
const KEYS=['albayanWorkspaceV1','albayanAccounts','albayanPendingInvoicesV1','albayanRejectedInvoicesV1','albayanCashHandoversV1','albayanRepVisitsV2','albayanRepDailyCloseV1','albayanRepLateActivityV1','albayanRepresentativeRouteV1','albayanRouteCycleV1','albayanRepProfileV1','albayanRepresentativesV1','albayanRepReceiptsV1','albayanReceiptSequenceV1','albayanDebtGraceDays'];
const SESSION='albayanCloudSessionV1',META='albayanCloudDeviceV1';
let busy=false,refreshing=null;
const read=(store,key,fallback)=>{const raw=store.getItem(key);return raw?JSON.parse(raw):fallback;};
const meta=()=>read(localStorage,META,{});
const session=()=>read(sessionStorage,SESSION,null);
function say(text){const el=document.getElementById('cloudMessage');if(el)el.textContent=text;const badge=document.getElementById('cloudBadge');if(badge)badge.textContent=text;}
function payload(){const result={};for(const k of KEYS){const v=localStorage.getItem(k);if(v!==null){JSON.parse(v);result[k]=v;}}return result;}
function validate(p){if(!p||Array.isArray(p)||typeof p!=='object')throw Error('صيغة النسخة غير صالحة');for(const [k,v] of Object.entries(p)){if(!KEYS.includes(k)||typeof v!=='string')throw Error('محتوى النسخة غير صالح');JSON.parse(v);}return p;}
async function request(path,body,token,method){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(URL_BASE+path,{method:method||(body?'POST':'GET'),headers:{apikey:API_KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null;}catch{throw Error('تعذّر قراءة رد الخادم');}if(!r.ok){const message=data?.message||data?.msg||data?.error_description||'تعذّر الاتصال';if(message.includes('CLOUD_CONFLICT'))throw Error('توجد نسخة أحدث من جهاز آخر. توقف الحفظ؛ نزّل نسخة جهازك ثم استرجع النسخة السحابية.');if(r.status===401)throw Error('انتهت الجلسة. سجّل الدخول من جديد.');if(message.includes('Invalid login'))throw Error('البريد أو كلمة المرور غير صحيحة.');if(message.includes('Email not confirmed'))throw Error('أكد بريدك الإلكتروني أولًا.');throw Error(message);}return data;}finally{clearTimeout(timeout);}}
function saveSession(s){s.expires_at=Date.now()+Number(s.expires_in||3600)*1000;sessionStorage.setItem(SESSION,JSON.stringify(s));}
async function token(){let s=session();if(!s)throw Error('سجّل الدخول إلى السحابة أولًا.');if(s.expires_at<Date.now()+60000){if(!refreshing)refreshing=request('/auth/v1/token?grant_type=refresh_token',{refresh_token:s.refresh_token}).then(saveSession).finally(()=>{refreshing=null;});await refreshing;s=session();}return s.access_token;}
async function current(){const t=await token();const user=await request('/auth/v1/user',null,t);return{t,user};}
async function remote(t){const rows=await request('/rest/v1/albayan_cloud_snapshots?select=payload,revision,updated_at',null,t);return rows[0]||null;}
async function fingerprint(p){const bytes=new TextEncoder().encode(JSON.stringify(Object.fromEntries(KEYS.filter(k=>k in p).map(k=>[k,p[k]]))));return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');}
async function upload(enable=false){if(busy)return;busy=true;try{const {t,user}=await current();let m=meta();if(m.userId&&m.userId!==user.id)throw Error('هذا المتصفح مرتبط بحساب سحابي آخر. استخدم متصفحًا منفصلًا للحساب الجديد.');if(!m.enabled&&!enable)return;const p=payload(),hash=await fingerprint(p);if(!m.enabled){const r=await remote(t);if(r)throw Error('توجد نسخة سحابية مسبقًا. نزّل نسخة جهازك ثم استرجع النسخة السحابية قبل تفعيل الحفظ.');m={userId:user.id,revision:0,enabled:true};}if(m.hash===hash){say('لا توجد تغييرات محلية جديدة للحفظ');return;}say('جارٍ الحفظ بالسحابة…');const revision=await request('/rest/v1/rpc/albayan_save_snapshot',{expected_revision:m.revision,document:p},t);localStorage.setItem(META,JSON.stringify({...m,revision,hash,lastSuccess:new Date().toISOString(),enabled:true}));say('تم الحفظ بالسحابة · '+new Date().toLocaleTimeString('ar-IQ'));}catch(e){say(e.name==='AbortError'?'انتهت مهلة الاتصال؛ بياناتك محفوظة على الجهاز.':e.message);throw e;}finally{busy=false;}}
function download(){const content=JSON.stringify({format:'albayan-cloud-backup-v1',payload:payload()},null,2);const url=window.URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='albayan-full-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>window.URL.revokeObjectURL(url),1000);}
async function restore(){if(busy)return;busy=true;try{const {t,user}=await current();const m=meta();if(m.userId&&m.userId!==user.id)throw Error('استخدم متصفحًا منفصلًا لهذا الحساب.');const r=await remote(t);if(!r)throw Error('لا توجد نسخة سحابية بعد.');const p=validate(r.payload);if(!confirm('استرجاع نسخة '+new Date(r.updated_at).toLocaleString('ar-IQ')+' يستبدل بيانات هذا المتصفح. أغلق صفحات البرنامج الأخرى أولًا. ستُحفظ نسخة تراجع محلية. متابعة؟'))return;const before=payload();localStorage.setItem('albayanCloudBeforeRestoreV1',JSON.stringify(before));try{for(const k of KEYS){if(k in p)localStorage.setItem(k,p[k]);else localStorage.removeItem(k);}localStorage.setItem(META,JSON.stringify({userId:user.id,revision:r.revision,hash:await fingerprint(p),enabled:true,lastSuccess:r.updated_at}));}catch(e){for(const k of KEYS){if(k in before)localStorage.setItem(k,before[k]);else localStorage.removeItem(k);}throw e;}say('تم الاسترجاع. افتح البرنامج من الرابط أدناه.');}finally{busy=false;}}
async function action(fn){if(busy)return;const buttons=[...document.querySelectorAll('#cloudPanel button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){say(e.message);}finally{buttons.forEach(b=>b.disabled=false);}}
function init(){const bar=document.createElement('div');bar.className='no-print';bar.style.cssText='padding:10px 16px;background:#e9f2fb;color:#123b63;font:14px Tahoma;display:flex;gap:12px;flex-wrap:wrap';const a=document.createElement('a');a.href='cloud.html';a.textContent='الحساب والحفظ السحابي';const badge=document.createElement('span');badge.id='cloudBadge';bar.append(a,badge);document.body.prepend(bar);say(session()?(meta().enabled?'الحفظ السحابي مفعّل لهذا الحساب':'سجّلت الدخول؛ فعّل الحفظ من صفحة الحساب'):'البيانات محلية · سجّل الدخول لتفعيل الحفظ السحابي');
const form=document.getElementById('cloudLogin');if(form){form.onsubmit=e=>{e.preventDefault();action(async()=>{const s=await request('/auth/v1/token?grant_type=password',{email:form.email.value.trim(),password:form.password.value});saveSession(s);form.password.value='';say('تم تسجيل الدخول. فعّل حفظ بيانات هذا الجهاز أو استرجع نسختك السحابية.');});};document.getElementById('cloudSignup').onclick=()=>{if(!form.reportValidity())return;action(async()=>{const s=await request('/auth/v1/signup',{email:form.email.value.trim(),password:form.password.value});form.password.value='';if(s.access_token){saveSession(s);say('تم إنشاء الحساب. اضغط تفعيل الحفظ.');}else say('راجع بريدك لتأكيد الحساب، ثم ارجع وسجّل الدخول هنا.');});};document.getElementById('cloudUpload').onclick=()=>action(()=>upload(true));document.getElementById('cloudRestore').onclick=()=>action(restore);document.getElementById('cloudDownload').onclick=()=>action(download);document.getElementById('cloudLogout').onclick=()=>action(async()=>{const t=await token();await request('/auth/v1/logout?scope=local',{},t);sessionStorage.removeItem(SESSION);say('تم تسجيل الخروج من السحابة. البيانات المحلية باقية على هذا الجهاز.');});document.getElementById('cloudUndo').onclick=()=>action(async()=>{const p=validate(read(localStorage,'albayanCloudBeforeRestoreV1',null));if(!confirm('التراجع عن آخر استرجاع؟ سيتوقف الحفظ السحابي حتى تعيد المراجعة.'))return;const before=payload();try{for(const k of KEYS){if(k in p)localStorage.setItem(k,p[k]);else localStorage.removeItem(k);}localStorage.setItem(META,JSON.stringify({...meta(),enabled:false}));}catch(e){for(const k of KEYS){if(k in before)localStorage.setItem(k,before[k]);else localStorage.removeItem(k);}throw e;}say('تم التراجع محليًا. نزّل نسخة قبل استئناف العمل.');});}
setInterval(()=>{if(session()&&meta().enabled&&navigator.onLine&&!document.hidden)upload().catch(()=>{});},15000);window.addEventListener('online',()=>{if(session()&&meta().enabled)upload().catch(()=>{});});}
window.AlbayanCloud={upload,restore,payload,validate};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
