(() => {
'use strict';
if (!/\/index\.html$/.test(location.pathname) && !location.pathname.endsWith('/albayan-accounting/')) return;
const css=`
@media(max-width:750px){
 body{padding-bottom:72px;background:#f4f7fb}header{padding:10px 14px;min-height:54px}header h1{font-size:19px}header p{font-size:11px}.system-links{display:none!important}nav{position:sticky;top:0;padding:7px 8px;gap:5px}nav button{min-height:38px;padding:6px 10px;font-size:12px}main{padding:10px 8px 78px}h2{font-size:19px;margin-bottom:10px}.panel{padding:10px;border-radius:11px;margin-bottom:10px}
 #sales>h2{background:#123b63;color:#fff;margin:-10px -8px 10px;padding:12px 14px;font-size:20px}#sales>.panel:first-of-type{padding:9px;border-radius:10px}#sales #saleTitle{font-size:17px;margin:0 0 8px;color:#123b63;border-bottom:1px solid #d9e3ed;padding-bottom:7px}.mobile-sale-actions{display:grid;grid-template-columns:1.25fr 1.25fr .8fr .8fr;gap:5px;margin:0 0 9px}.mobile-sale-actions button{min-height:38px!important;padding:5px!important;font-size:11px!important}.mobile-sale-actions .save{background:#123b63;color:#fff}.mobile-sale-actions .print{background:#1769aa;color:#fff}#saleForm>.grid:first-of-type{grid-template-columns:1fr 1fr!important;gap:6px}#saleForm>.grid:first-of-type label{font-size:11px;gap:2px}#saleForm>.grid:first-of-type input,#saleForm>.grid:first-of-type select{min-height:36px;padding:5px 7px;font-size:13px;border-radius:6px}#saleForm>.muted,#saleForm>.remember-tier,#tierHint{font-size:11px;margin:6px 0;padding:6px}
 #saleLines{margin-top:8px;border-top:1px solid #d9e3ed;counter-reset:saleitem}.sale-line{counter-increment:saleitem;position:relative;grid-template-columns:1.35fr .65fr!important;gap:6px;padding:30px 8px 9px!important;margin:7px 0;background:#fff;border:1px solid #d9e3ed!important;border-radius:9px}.sale-line:before{content:'الصنف ' counter(saleitem);position:absolute;top:6px;right:8px;font-size:11px;font-weight:bold;color:#123b63}.sale-line label:first-child{grid-column:1/-1!important}.sale-line label{font-size:11px;gap:2px}.sale-line input,.sale-line select{min-height:38px;padding:5px 7px;font-size:13px}.sale-line button{min-height:36px;padding:4px 9px}.sale-line .line-total{font-size:13px;font-weight:bold;margin:2px 0;grid-column:1/-1;background:#eef4f9;padding:7px;border-radius:6px;color:#123b63}.sale-line label:first-child select{font-size:14px;font-weight:bold}.sale-line input[type=number]{text-align:center;font-weight:bold}#sales .actions{gap:5px;margin-top:8px}#sales .actions button{min-height:38px;padding:6px 9px;font-size:12px}#sales .actions .primary{background:#123b63;color:white}#addSaleLine{width:100%;border:1px dashed #1769aa;background:#eef5fb;color:#123b63;font-weight:bold;min-height:42px!important}#saleForm>.grid[style]{grid-template-columns:repeat(3,1fr)!important;gap:6px!important;margin-top:9px!important}#saleForm>.grid[style] label{font-size:11px}#saleForm>.grid[style] input{min-height:36px}.sale-total{padding:10px 8px;font-size:14px;font-weight:bold;gap:6px;display:grid!important;grid-template-columns:1fr 1fr;background:#f7f9fc;border:1px solid #d9e3ed;border-radius:8px}.mobile-invoice-summary{margin-top:8px;border:1px solid #cbd9e7;border-radius:9px;background:#fff;overflow:hidden}.mobile-invoice-summary .row{display:flex;justify-content:space-between;align-items:center;padding:8px 10px;border-bottom:1px solid #e4ebf2;font-size:13px}.mobile-invoice-summary .row:last-child{border-bottom:0}.mobile-invoice-summary .value{font-weight:bold;font-variant-numeric:tabular-nums}.mobile-invoice-summary .grand{background:#123b63;color:#fff;font-size:18px;padding:11px 10px}.mobile-invoice-summary .previous[hidden]{display:none!important}#sales>.panel:last-child .toolbar{margin-bottom:7px}#sales>.panel:last-child .toolbar h3{font-size:15px;margin:0}#saleSearch{min-height:36px}#sales table{font-size:11px}#sales th,#sales td{padding:7px 5px}.cards{gap:7px;margin-bottom:10px}.card{padding:10px}.card strong{font-size:18px;margin-top:4px}.card span{font-size:11px}#home .panel{margin-bottom:9px}#home .actions{gap:5px;margin-top:8px}#home .actions button{min-height:38px;padding:6px 9px;font-size:12px}
 .mobile-bottom{position:fixed;bottom:0;right:0;left:0;height:62px;background:#123b63;display:grid;grid-template-columns:repeat(5,1fr);z-index:20;box-shadow:0 -3px 12px #0002;padding-bottom:env(safe-area-inset-bottom)}.mobile-bottom button{border:0;border-radius:0;background:transparent;color:#dce9f5;min-height:58px;padding:4px 2px;font-size:10px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px}.mobile-bottom button b{font-size:19px;line-height:1}.mobile-bottom button.active{background:#1769aa;color:white}#offlineStatus{font-size:10px!important;padding:5px 8px!important;min-height:0!important}
}
@media(max-width:420px){#saleForm>.grid[style]{grid-template-columns:1fr 1fr!important}}
@media(min-width:751px){.mobile-bottom,.mobile-sale-actions,.mobile-invoice-summary{display:none!important}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
function money(n){const x=Number(n)||0;return x.toLocaleString('ar-IQ',{maximumFractionDigits:2})+' د.ع'}
function discountValue(){return Math.max(0,Number(document.getElementById('saleDiscount')?.value)||0)}
function grossInvoiceAmount(){if(typeof draftLines!=='undefined'&&typeof lineCents==='function'&&typeof cents==='function'){const loading=Number(document.getElementById('saleLoading')?.value)||0;const raw=(draftLines.reduce((n,l)=>n+lineCents(l),0)+cents(loading))/100;return Number.isFinite(raw)?raw:0}return 0}
function previousBalance(){const name=(document.getElementById('saleCustomer')?.value||'').trim();if(!name||typeof allAccounts!=='function')return 0;const editId=typeof saleEdit!=='undefined'?saleEdit:null;return allAccounts().filter(a=>(a.customer||'').trim()===name&&(!editId||a.invoiceId!==editId)).reduce((s,a)=>s+(Number(a.owedBy)||0)-(Number(a.owedTo)||0),0)}
function updateSummary(){const sum=document.querySelector('.mobile-invoice-summary');if(!sum)return;const gross=grossInvoiceAmount(),discount=discountValue(),current=Math.max(0,gross-discount),prev=Math.max(0,previousBalance());sum.querySelector('[data-invoice-amount]').textContent=money(gross);sum.querySelector('[data-discount]').textContent=money(discount);const p=sum.querySelector('.previous');p.hidden=!(prev>0);sum.querySelector('[data-previous]').textContent=money(prev);sum.querySelector('[data-grand]').textContent=money(current+prev)}
function addSummary(){if(document.querySelector('.mobile-invoice-summary'))return;const totals=document.getElementById('saleTotals');if(!totals)return;const box=document.createElement('div');box.className='mobile-invoice-summary';box.innerHTML='<div class="row"><span>مبلغ الفاتورة</span><span class="value" data-invoice-amount>0 د.ع</span></div><div class="row previous" hidden><span>الرصيد السابق</span><span class="value" data-previous>0 د.ع</span></div><div class="row"><span>الخصم</span><span class="value" data-discount>0 د.ع</span></div><div class="row grand"><span>المبلغ الكلي</span><span class="value" data-grand>0 د.ع</span></div>';totals.after(box);const obs=new MutationObserver(updateSummary);obs.observe(totals,{childList:true,subtree:true,characterData:true});document.getElementById('saleCustomer')?.addEventListener('input',updateSummary);document.getElementById('saleCustomer')?.addEventListener('change',updateSummary);updateSummary()}
function installDiscount(){const form=document.getElementById('saleForm'),paid=document.getElementById('salePaid');if(!form||!paid||document.getElementById('saleDiscount'))return;const label=document.createElement('label');label.innerHTML='الخصم · د.ع<input id="saleDiscount" type="number" min="0" step="0.01" value="0" required>';paid.closest('.grid')?.insertBefore(label,paid.parentElement);const input=label.querySelector('input');const baseInvoiceTotal=typeof invoiceTotal==='function'?invoiceTotal:null;const baseInvoiceHTML=typeof invoiceHTML==='function'?invoiceHTML:null;const baseUpdateTotals=typeof updateSaleTotals==='function'?updateSaleTotals:null;const baseSaleTransaction=typeof saleTransaction==='function'?saleTransaction:null;if(baseInvoiceTotal){invoiceTotal=function(v){const gross=baseInvoiceTotal({...v,discount:undefined});return (cents(gross)-cents(Number(v.discount)||0))/100}}
 if(baseSaleTransaction){saleTransaction=function(s,v,edit){const discount=discountValue();const gross=(v.lines.reduce((n,l)=>n+lineCents(l),0)+cents(v.loading))/100;if(discount>gross)throw Error('الخصم لا يمكن أن يكون أكبر من مبلغ الفاتورة.');const afterDiscount=(cents(gross)-cents(discount))/100;if(cents(v.paid)>cents(afterDiscount))throw Error('المبلغ المدفوع لا يمكن أن يكون أكبر من المجموع بعد الخصم.');v.discount=discount;return baseSaleTransaction(s,v,edit)}}
 if(baseUpdateTotals){updateSaleTotals=function(){const gross=grossInvoiceAmount(),discount=discountValue(),total=(cents(gross)-cents(discount))/100;if(discount>gross){document.getElementById('saleTotals').textContent='الخصم لا يمكن أن يكون أكبر من مبلغ الفاتورة.';updateSummary();return NaN}const paidNow=Number(document.getElementById('salePaid').value)||0;if(cents(paidNow)>cents(total)){document.getElementById('saleTotals').textContent='المبلغ المدفوع لا يمكن أن يكون أكبر من المجموع بعد الخصم.';updateSummary();return NaN}document.getElementById('saleTotals').textContent=`مبلغ الفاتورة: ${money(gross)} · الخصم: ${money(discount)} · المجموع بعد الخصم: ${money(total)} · المتبقي: ${money((cents(total)-cents(paidNow))/100)}`;updateSummary();return total}}
 if(baseInvoiceHTML){invoiceHTML=function(v){let html=baseInvoiceHTML(v);const d=Number(v.discount)||0;if(d>0)html=html.replace('<p class="grand"><span>المجموع الكلي</span>',`<p><span>الخصم</span><b>${money(d)}</b></p><p class="grand"><span>المجموع الكلي</span>`);return html}}
 input.addEventListener('input',()=>{if(typeof updateSaleTotals==='function')updateSaleTotals();updateSummary()});document.addEventListener('click',e=>{const b=e.target.closest('[data-edit-sale]');if(!b)return;setTimeout(()=>{const v=typeof state!=='undefined'?state.invoices.find(x=>x.id===b.dataset.editSale):null;input.value=String(Number(v?.discount)||0);if(typeof updateSaleTotals==='function')updateSaleTotals()},0)});if(typeof updateSaleTotals==='function')updateSaleTotals()}
let printAfterSave=false,printBeforeInvoiceId=null;
function tryPrintSavedInvoice(){if(!printAfterSave)return;const view=document.getElementById('invoiceView');const current=typeof viewedInvoice!=='undefined'?viewedInvoice:null;if(view&&!view.hidden&&current&&current!==printBeforeInvoiceId){printAfterSave=false;printBeforeInvoiceId=null;document.getElementById('printInvoice')?.click()}}
function addSaleActions(){if(document.querySelector('.mobile-sale-actions'))return;const form=document.getElementById('saleForm'),title=document.getElementById('saleTitle');if(!form||!title)return;const bar=document.createElement('div');bar.className='mobile-sale-actions no-print';bar.innerHTML='<button type="button" class="save" data-fast-save>حفظ</button><button type="button" class="print" data-fast-save-print>حفظ وطباعة</button><button type="button" data-fast-new>جديد</button><button type="button" data-fast-reset>إلغاء</button>';title.after(bar);bar.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-fast-save')){printAfterSave=false;printBeforeInvoiceId=null;form.requestSubmit();return}if(b.hasAttribute('data-fast-save-print')){printAfterSave=true;printBeforeInvoiceId=typeof viewedInvoice!=='undefined'?viewedInvoice:null;form.requestSubmit();let tries=0;const timer=setInterval(()=>{tries++;tryPrintSavedInvoice();if(!printAfterSave||tries>=20){clearInterval(timer);if(tries>=20){printAfterSave=false;printBeforeInvoiceId=null}}},100);return}if(b.hasAttribute('data-fast-new')||b.hasAttribute('data-fast-reset')){printAfterSave=false;printBeforeInvoiceId=null;document.getElementById('resetSale')?.click()}});}
function addBottom(){if(document.querySelector('.mobile-bottom'))return;const bar=document.createElement('div');bar.className='mobile-bottom no-print';bar.innerHTML='<button data-mob="home"><b>⌂</b>الرئيسية</button><button data-mob="purchaseOrders"><b>▣</b>المشتريات</button><button data-mob="sales"><b>▤</b>المبيعات</button><button data-mob="accounts"><b>◉</b>الصندوق</button><button data-mob="backup"><b>▦</b>التقارير</button>';document.body.appendChild(bar);bar.addEventListener('click',e=>{const b=e.target.closest('[data-mob]');if(!b)return;const target=document.querySelector('nav button[data-page="'+b.dataset.mob+'"]');if(target)target.click();setActive(b.dataset.mob)});setActive('home')}
function setActive(page){document.querySelectorAll('.mobile-bottom button').forEach(b=>b.classList.toggle('active',b.dataset.mob===page))}
function init(){installDiscount();addSaleActions();addSummary();addBottom()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b&&b.dataset.page)setActive(b.dataset.page)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();