'use strict';
const VERSION='offline-20260912-37';
const BASE=new URL('./',self.location.href),PREFIX='qarya-shell:'+BASE.pathname+':',CACHE=PREFIX+VERSION;
const FILES=['index.html','start.html','cloud.html','representative.html','representative-dashboard.html','representative-sale.html','rep-sales-v2.html','rep-payment-v2.html','rep-receipts-v2.html','payment-schedule.html','collection-statement.html','rep-reports-v2.html','admin-dashboard.html','admin-control.html','representatives.html','cash-handover.html','rep-daily-close.html','route-order.html','purchases.html','purchase-order.html','purchase-list.html','stock-orders.js','stock-orders-ui.js','purchase-list-ui.js','purchase-order-design.js','print-scope-ui.js','mobile-ui.js','mobile-home-fix.js','sales-account-ui.js','sales-price-fix.js','sales-payment-ui.js','sales-balance-ui.js','sales-print-ui.js','customer-payment-ui.js','customer-balance-engine.js','invoice-cancel-safety.js','account-transaction-safety.js','cash-ui.js','reports-ui.js','backup-extra-ui.js','sync-core.js','central-sync-transport.js','rep-safety.js','material-import.js','material-import-ui.js','rep-purchase-report.js','cloud-sync.js','rep-payment-upgrade.js','rep-simple-ui.js','rep-statement-fix.js','rep-daily-summary.js','rep-order-management.js','rep-sales-unit-fix.js','rep-fifo-balance-fix.js','rep-reports-upgrade.js','rep-dashboard-fix.js','admin-order-status.js','offline.js','manifest.webmanifest','icons/qarya-wordmark-180.png','icons/qarya-wordmark-192.png','icons/qarya-wordmark-512.png','icons/qarya-wordmark-maskable-512.png'];
const URLS=FILES.map(f=>new URL(f,BASE).href),ALLOWED=new Set(URLS);
function paymentPageUrl(u){return u.pathname.endsWith('/rep-payment-v2.html')}
function indexPageUrl(u){return u.pathname.endsWith('/index.html')}
function balancePageUrl(u){return paymentPageUrl(u)||indexPageUrl(u)||u.pathname.endsWith('/representative.html')||u.pathname.endsWith('/payment-schedule.html')}
async function prepareResponse(u,response){if(!balancePageUrl(u))return response;const text=await response.text();let body=text;const inject=[];if(!body.includes('customer-balance-engine.js'))inject.push('<script src="customer-balance-engine.js?v=20260912-37"></script>');if(paymentPageUrl(u)&&!body.includes('rep-fifo-balance-fix.js'))inject.push('<script src="rep-fifo-balance-fix.js?v=20260912-37"></script>');if(indexPageUrl(u)){if(!body.includes('invoice-cancel-safety.js'))inject.push('<script src="invoice-cancel-safety.js?v=20260912-37"></script>');if(!body.includes('account-transaction-safety.js'))inject.push('<script src="account-transaction-safety.js?v=20260912-37"></script>')}if(inject.length){const tag=inject.join('');body=body.includes('</body>')?body.replace('</body>',tag+'</body>'):body+tag}return new Response(body,{status:response.status,statusText:response.statusText,headers:response.headers})}
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);for(const href of URLS){try{const u=new URL(href),fresh=await fetch(new Request(href,{cache:'no-store'}));if(fresh.ok){const ready=await prepareResponse(u,fresh);await c.put(href,ready.clone())}}catch(err){console.warn('offline cache skip',href,err)}}await self.skipWaiting()})()));
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith(PREFIX)&&k!==CACHE)await caches.delete(k);await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==BASE.origin||!u.pathname.startsWith(BASE.pathname))return;if(u.pathname===BASE.pathname)u.pathname+='start.html';u.search='';u.hash='';if(!ALLOWED.has(u.href))return;e.respondWith((async()=>{const c=await caches.open(CACHE);try{const fresh=await fetch(new Request(u.href,{cache:'no-store'}));if(fresh&&fresh.ok){const ready=await prepareResponse(u,fresh);await c.put(u.href,ready.clone());return ready}}catch(_){}const x=await c.match(u.href);return x||fetch(r)})())});